ogit:
    branch: master

wants:
    mongo: true

health:
  path: /version

secrets:
  - SESSION_SECRET
  - EMAIL_KEY
  - GROUND_TRUTH_URL
  - GROUND_TRUTH_ID
  - GROUND_TRUTH_SECRET
  - GCS_REGION
  - GCS_BUCKET
  - GCS_CLIENT_EMAIL
  - GCS_PRIVATE_KEY
  - GCS_UPLOAD_DIRECTORY
  - REGISTRATION_URL
  - REGISTRATION_KEY
  - BUGSNAG
  - API_KEY


env:
  COOKIE_SECURE_ONLY: true
  EMAIL_FROM: "HackGT Team <hello@hackgt.com>"
  PRODUCTION: true
  ADMIN_DOMAINS: 'hack.gt'
